services:
  bc3_nonkyc:
    image: nginx:alpine
    container_name: bc3_nonkyc
    restart: unless-stopped

      #    ports:
      #- "1337:80"

    volumes:
      - ./html:/usr/share/nginx/html:ro

    networks:
      - proxy

networks:
  proxy:
    external: true

